# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: pt-BR

# Site title
title: "Icaro Carmona de Almeida"

# A description of your site for meta tag, search engine results.
description: "OlÃ¡ ðŸ‘‹! Esse Ã© meu espaÃ§o, onde pretendo escrever sobre Tecnologia, Dados, Arquitetura e IA."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://icarocarmona.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Tags
    url: /tags/
  - text: Download
    url: /

# The shortname for your Disqus site to enable comments.
disqus: icarocarmona

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
